### PR TITLE
apply cors header methods typo

### PR DESCRIPTION
**Pull request by lrlna**
Hey :wave: ! I noticed that there may be a typo when you're applying `cors` methods 🙊 🙈 

p.s. super clear cors implementation; a+++ ^_^

### CODE REVIEW

**Review by toddself — APPROVED** [review]
🚋

**Comment by toddself** [comment]
💖 ! Thank you!

**Comment by toddself** [comment]
Published as 1.3.3

**Comment by lrlna** [comment]
any time ^__^

**Pull request merged**
